=== abhijd88/XML_XSD_validation_OverWebClient/schemas/order_details.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <!--********************************************
    ********definition of simple types**************
    **********************************************-->


    <!-- Types relating to the "ordered_by" element inside the complex element "order_details" -->
    <xs:complexType name="ordered_by_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string" />
            <xs:element name="email" type="email_type"  maxOccurs="unbounded"/>
            <xs:element name="phone" type="phone_type"  maxOccurs="unbounded"/>
            <xs:element name="address" type="address_type" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="email_type">
        <xs:restriction base="xs:string">
            <xs:pattern value=".*@.*\..*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="phone_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]*"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:complexType name="address_type">
        <xs:sequence>
            <xs:element name="line1" type="xs:string"/>
            <xs:element name="line2" type="xs:string" minOccurs="0"/>
            <xs:element name="city" type="xs:string"/>
            <xs:element name="country" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    <!-- Types relating to the "ordered_items" element inside the complex element "order_details" -->
    <xs:complexType name="ordered_items_type">
        <xs:sequence>
            <xs:element name="item" type="item_type"  maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="item_type">
        <xs:sequence>
            <xs:element name="name" type="xs:string" minOccurs="0"/>
            <xs:element name="quantity" type="xs:positiveInteger" />
            <xs:element name="frame" type="design_type" />
            <xs:element name="screen" type="design_type" />
            <xs:element name="keypad" type="design_type" />
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="design_type">
        <xs:sequence>
            <xs:element name="design" type="choose_abc_type"/>
            <xs:element name="color" type="color_type"/>
        </xs:sequence>
    </xs:complexType>
    <xs:simpleType name="color_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="red|blue|green|Red|Blue|Green|RED|BLUE|GREEN"/>
        </xs:restriction>
    </xs:simpleType>
    <xs:simpleType name="choose_abc_type">
        <xs:restriction base="xs:string">
            <xs:pattern value="[ABCabc]"/>
        </xs:restriction>
    </xs:simpleType>

    <!--********************************************
    ********definition of complex elements *********
    *********************************************-->

    <xs:element name="order_details">
        <xs:complexType>
            <xs:all>
                <xs:element name="ordered_by" type="ordered_by_type"/>
                <xs:element name="ordered_items" type="ordered_items_type"/>
                <xs:element name="order_date" type="xs:date"/>
                <xs:element name="order_id" type="xs:string"/>
            </xs:all>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== abhijd88/XML_XSD_validation_OverWebClient/uploads/order2.xml
<?xml version="1.0" encoding="UTF-8"?>

<order_details  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="order_details.xsd">
    <ordered_by>
        <name>Abhijit</name>
        <email>abhi@abhi.com</email>
        <phone>0231145</phone>
        <address>
            <line1>street address 1</line1>
            <line2>street 2</line2>
            <city>Tampere</city>
            <country>Finland</country>
        </address>
    </ordered_by>
    <order_id>s39232</order_id>
    <order_date>2017-01-31</order_date>
    <ordered_items>
        <item>
            <name>Item1</name>
            <quantity>8</quantity>
            <frame>
                <design>A</design>
                <color>Red</color>
            </frame>
            <screen>
                <design>A</design>
                <color>Red</color>
            </screen>
            <keypad>
                <design>A</design>
                <color>blue</color>
            </keypad>
        </item>
        <item>
            <name>Item2</name>
            <quantity>6</quantity>
            <frame>
                <design>c</design>
                <color>blue</color>
            </frame>
            <screen>
                <design>A</design>
                <color>Red</color>
            </screen>
            <keypad>
                <design>B</design>
                <color>GREEN</color>
            </keypad>
        </item>
    </ordered_items>

</order_details>
